#!/bin/sh

## Clone configuration files from GitHub
#
# git clone https://github.com/adavis444/debian-config.git
#
# Execute this script:
# sh ~/debian-config/how-to-set-up-chromebook-linux


## Link Chromebook folders to Linux home directory
#
# Open Files app
# For each [My files/Downloads, Google Drive/My Drive, sd]:
# 	Right click
# 	Share with Linux
ln -s /mnt/chromeos/GoogleDrive/MyDrive ~/google-drive
ln -s /mnt/chromeos/MyFiles/Downloads ~/downloads
ln -s /mnt/chromeos/removable/sd ~/sd
