#!/bin/bash

PYTHON_VERSION=3.9.6

source git_pull_if_exists_else_clone.sh

## Install python and pyenv
gitPullIfExistsElseClone https://github.com/pyenv/pyenv.git \
	$HOME/.pyenv

if [[ ":$PATH:" != *":$HOME/.pyenv/bin:"* ]]; then
	export PATH=$HOME/.pyenv/bin:$PATH
fi
eval "$(pyenv init -)"

pyenv install $PYTHON_VERSION --skip-existing
pyenv global $PYTHON_VERSION

## Install pyenv-virtualenv
#gitPullIfExistsElseClone https://github.com/pyenv/pyenv-virtualenv.git \
#	$HOME/.pyenv/plugins/pyenv-virtualenv
#eval "$(pyenv virtualenv-init -)"
