#!/bin/bash

source git_pull_if_exists_else_clone.sh

gitPullIfExistsElseClone https://github.com/rbenv/rbenv.git $HOME/.rbenv
cd ~/.rbenv && src/configure && make -C src
cd - >/dev/null

mkdir -p $HOME/.rbenv/plugins
gitPullIfExistsElseClone https://github.com/rbenv/ruby-build.git \
	$HOME/.rbenv/plugins/ruby-build

if [[ ":$PATH:" != *":$HOME/.rbenv/bin:"* ]]; then
	export PATH=$HOME/.rbenv/bin:$PATH
fi

eval "$(rbenv init -)"

rbenv install 2.6.5 --skip-existing
rbenv global 2.6.5

gem install rails
