#!/bin/bash

## Prepare folders to share with Linux
# Open Files app
# For each [My files/Downloads, Google Drive/My Drive, sd]:
# 	Right click
# 	Share with Linux

## Clone configuration files from GitHub
# 	git clone https://github.com/adavis444/debian-config.git
# Execute this script:
# 	bash $HOME/debian-config/set-up-chromebook-linux

source $HOME/debian-config/git_pull_if_exists_else_clone.sh
source $HOME/debian-config/create_symlink_from_mnt.sh

sudo apt full-upgrade -y
sudo apt install -y coreutils sudo git

gitPullIfExistsElseClone https://github.com/adavis444/debian-config.git \
	$HOME/debian-config

## Overwrite default hidden files with available soft links
for f in $(ls -A $HOME/debian-config | grep "^\."); do
	if [ -f $HOME/debian-config/$f ]; then
		ln -sf $HOME/debian-config/$f $HOME/$f
	fi
done

## Link Chromebook folders to Linux home directory
createSymlinkFromMnt /mnt/chromeos/GoogleDrive/MyDrive $HOME/google-drive
createSymlinkFromMnt /mnt/chromeos/MyFiles/Downloads $HOME/downloads
createSymlinkFromMnt /mnt/chromeos/removable/sd $HOME/sd

## Install packages from apt
sudo apt install -y $(cat $HOME/debian-config/apt-packages | tr "\n" " ")

## Set up Vundle
gitPullIfExistsElseClone https://github.com/VundleVim/Vundle.vim.git \
	$HOME/.vim/bundle/Vundle.vim
