#!/bin/sh

## Prepare folders to share with Linux
# Open Files app
# For each [My files/Downloads, Google Drive/My Drive, sd]:
# 	Right click
# 	Share with Linux

## Clone configuration files from GitHub
# 	git clone https://github.com/adavis444/debian-config.git
# Execute this script:
# 	sudo sh "$HOME/debian-config/set-up-chromebook-linux"

## Overwrite default hidden files with available soft links
for f in $(ls -ap "$HOME/debian-config/" | grep "^\..*[^/]$")
do
	ln -sf "$HOME/debian-config/$f" "$HOME/$f"
done

## Link Chromebook folders to Linux home directory
sudo ln -sf /mnt/chromeos/GoogleDrive/MyDrive "$HOME/"
sudo ln -sf /mnt/chromeos/MyFiles/Downloads "$HOME/"
sudo ln -sf /mnt/chromeos/removable/sd "$HOME/"

## Install node and npm
curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
sudo apt install -y nodejs

## Install yarn
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt install -y yarn

## Set up vim with Vundle and YouCompleteMe
sudo apt install -y vim-nox
git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
vim +PluginInstall +qall
sudo apt install -y build-essential cmake python3-dev
python3 "$HOME/.vim/bundle/YouCompleteMe/install.py" --clangd-completer --ts-completer --rust-completer

## Install python and pyenv
sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
exec "$SHELL"
pyenv install 3.7.5
pyenv global 3.7.5
pip install --upgrade pip
pip install numpy pandas requests

## Install pyenv-virtualenv
#git clone https://github.com/pyenv/pyenv-virtualenv.git "$HOME/.pyenv/plugins/pyenv-virtualenv"
# Enable the following line in .bashrc:
# eval "$(pyenv virtualenv-init -)"
#exec "$SHELL"

## Unrelated
sudo apt install -y lsb-release
